<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Version details.
 *
 * @package    local_grupomakro_core
 * @copyright  2022 Solutto Consulting <devs@soluttoconsulting.com>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
defined('MOODLE_INTERNAL') || die();

$plugin->component = "local_grupomakro_core";
$plugin->version   = 20260701007;         // overdue_grace_days admin setting + local_grupomakro_get_overdue_grace_days AJAX action for server-to-server Express lookup; configurable from financial settings page, default 3, consumed by Express rest_express/server.js instead of hard-coded constant.
$plugin->version   = 20260701008;         // Module enrollment gated by Odoo invoice (gmk_module_invoice_requests) — mirrors revalidation flow with MODULE_REQ:<id> ref, payment-gated enroll_module, refresh-payment action, 30-day expiry cron, LXP pending modules section.
$plugin->version   = 20260801002;         // Academic Director Revalidations Dashboard (pages/revalidations_director.php): 4 new WS (list/refresh_one/refresh_bulk/get_classes/get_eligible/create_extemp), new capabilities view_revalidations_dashboard + create_extemporaneous_revalidations, academic-calendar window gate on teacher schedule action, gmk_revalidations.extemporaneous* audit columns, extemporaneous creation by director bypassing the window but enforcing eligibility (60.0–70.9 sin horas prácticas).
$plugin->version   = 20260802000;         // Failed Subjects Report (pages/failed_subjects_report.php + classes/local/failed_subjects_manager.php + 5 new WS in classes/external/admin/failed_subjects/): students with status 5/7 in gmk_course_progre matched against gmk_class projected in a chosen period by jornada, quota, and availability; contact lookup via Odoo Express proxy with TTL cache; force-over-quota enrolment with audit log in gmk_class_absence_history. Two new capabilities view_failed_subjects_report and enrol_from_failed_subjects_report.
$plugin->version   = 20260803000;         // Admin broadcast messages (gmk_admin_message + gmk_admin_message_ack + gmk_admin_message_user): info/warning notices to students with career/group audience targeting, optional acknowledgement checkbox and configurable ack label, per-career acknowledgement stats, capability manageannouncements, dedicated admin page (pages/announcements.php) and Vue component (js/components/announcements.js). LXP store/components/announcements with priority-based precedence over AbsenceAlertSystem.
$plugin->version   = 20260804000;         // Failed Subjects Report enhancements: grade calculation via gradebookWeightedTotal matching grademodal.js exactly; quota count via get_class_participants (matches list_classes); new student_status filter (activo/aplazado/retirado/...); new "Ver grupos" picker showing all available gmk_class for a (course, period) with jornada/cupo match; new "Refrescar estado financiero" button calling local_grupomakro_refresh_financial_status_failed_subjects; new WS refresh_financial_status.php.
$plugin->version   = 20260805000;         // Individual course certificates: new gmk_diploma_eligible_course table (admin-managed per-course eligibility), nullable courseid column on gmk_diploma_generation, manager methods to list/toggle courses, count eligible students per course, list students for a course, compute eligibility, generate PDF per (student, course) pair; new "Por curso" tab in diplomageneration.php with the same Solo pendientes toggle UX as the existing "Estudiantes elegibles" section; admin sub-section in diplomatemplates.php to toggle which courses are eligible.
$plugin->version   = 20260805001;         // Revert homologation flow: WS local_grupomakro_revert_homologation clears the homologation fields on gmk_course_progre, resets status to Disponible and nulls Nota Final Integrada / course total grade_grades.
$plugin->version   = 20260805002;         // Homologation audit log: gmk_homologation_audit table + WS local_grupomakro_get_homologation_audit surfaces the chronological list of homologate/revert actions in the academic panel timeline dialog.
$plugin->version   = 20260806000;         // Per-session is_revalida flag: new column on attendance_sessions + index, auto-backfill for [Mon 06-Jul .. Sat 11-Jul 2026] marking the last session per class as revalida, filter applied to all attendance-grade SQL sites (course_grade_resolver, gmk_batch_weighted_grades, get_student_gradebook, get_student_course_pensum_activities, get_student_learning_plan_pensum, get_course_absences_detail, gmk_count_pending_attendance_sessions, gmk_mark_pending_sessions_as_absent, absence_helpers), ajax toggle endpoint local_grupomakro_toggle_session_revalida, dry-run + apply CLI scripts for the backfill.
$plugin->version   = 20260807000;         // PERFORMANCE: gmk_log() now no-ops unless GMK_DEBUG_LOG is defined; declared 8 new MUC caches (gmkclass_enriched, gmkinstructor, gmklearningplan, gmklearningperiod, gmkcoursecache, gmkclassroom, gmkbbbatrel, gmkattendancesession) and gmk_muc() helper. Rewrote list_classes() with bulk prefetch (subjects, instructors, plans, periods, courses, classrooms, customfields, participants) replacing N+1. Rewrote get_class_events() to bulk-prefetch attendance_sessions + gmk_bbb_attendance_relation + course_modules + user roles per event loop; new gmk_complete_class_event_information_fast / _bbb_fast / _generic_fast handlers drop-in compatible with the originals. Range clamp to 12 months. BUGFIX: student_get_active_classes() now filters gmk_course_progre by userid (was returning rows from every user in the plan).
$plugin->version   = 20260808000;         // Copy session feature: new WS local_grupomakro_check_copy_conflicts + local_grupomakro_copy_activity; gmk_copy_class_activity() in locallib.php creates up to 20 additional attendance_sessions + BBB + gmk_bbb_attendance_relation entries from a source session, extends enddate, updates assigned_dates. UI in ClassSchedule.js: teacher button + admin menu item, modal with dynamic list of date/time rows, conflict verification with force option.
$plugin->version   = 20260809000;         // Delete session feature: new WS local_grupomakro_delete_session + gmk_delete_class_activity() in locallib.php deletes the attendance_sessions row, its calendar event, the gmk_bbb_attendance_relation row, and (via course_delete_module) the BBB course_module + bigbluebuttonbn instance. Refuses when attendance_log records exist unless force=1; always writes a JSON backup to dataroot first. UI in ClassSchedule.js: admin menu item with confirmation modal that pre-checks log count and offers force option.
$plugin->version   = 20260810000;         // BUGFIX copy/delete 0-copied: renamed ClassSchedule.js -> ClassSchedule.v2.js (cache-bust). Frontend now uses URLSearchParams (URL-encoded) for copy_activity, check_copy_conflicts, and delete_session WS calls. Backend copy_activity.php and check_copy_conflicts.php accept dates as PHP array or JSON string (defense in depth for Moodle's PARAM_RAW + multipart auto-decode). Added frontend console.log diagnostics in sendCopy() so future issues can be triaged from the browser console.
$plugin->version   = 20260811000;         // Defensive data() in ClassSchedule.cpfix.js (renamed v3->cpfix) so the component mounts even if window.strings/strings reschedule causes are missing. pages/schedules.php now uses ?v=cpfix1 cache-bust query string on all JS assets to invalidate any theme/javascript.php cache.
$plugin->version   = 20260809001;         // Server-side paginated classmanagement view: new WS local_grupomakro_list_classes_paged with search/periodid/learningplanid/corecourseid/status/sort/dir/page/perpage filters; new classes/local/class_query_manager.php (build_where, count_filtered, fetch_page, list_class_facets) that reuses the existing list_classes() bulk-prefetch; new amd/src/class_management_filters.js with debounced search, filter persistence (query string + localStorage), grid/list re-render from JSON; pages/classmanagement.php and templates/class_management.mustache refactored to a shell + filter bar + paginator; 8 new indexes on gmk_class (closed, periodid, learningplanid, corecourseid, timecreated, courseid, plus composite closed+periodid+timecreated) and course.fullname.
$plugin->version   = 20260812000;         // Homologation Manager: reusable origin->destination course homologation rules (gmk_homologation_rules), preview of pending homologations across students enrolled in both plans using RESOLVED grades (course_grade_resolver, not the stale gmk_course_progre snapshot), and bulk apply via homologate_course_grade. New page pages/homologation_manager.php, js/components/homologationmanager.js, classes/local/homologation_engine.php and 6 WS in classes/external/homologation/.
$plugin->version   = 20260813000;         // Diploma consecutive bundles: new gmk_diploma_consecutive_bundle table (name, prefix, next_number, active), nullable bundle_id column on gmk_diploma_template, manager methods (list_bundles, save_bundle, delete_bundle, generate_bundle_number), dispatcher actions, diplomatemplates.php admin section to manage bundles and assign templates to them, frontend dropdown in template editor. Templates assigned to a bundle share its prefix + next counter so admins can keep an external sequence alive without knowing the exact number of diplomas per template.
$plugin->version   = 20260814000;         // PERFORMANCE: teacher dashboard initial load dropped from 15-19s to <2.5s. Removed calendar_events from local_grupomakro_get_teacher_dashboard_data (frontend now fetches them lazily via local_grupomakro_calendar_get_calendar_events when the 'Ver Calendario Completo' dialog opens). Added teacher_dashboard MUC cache (TTL 120s) keyed by (userid, YYYYMMDD) so warm renders are instant. Also: get_class_events now includes courses where the user holds teacher/editingteacher role_assignments (was: only groups_members, so teachers without any group membership got an empty calendar) and skips the group-scope post-filter when the user has no group memberships (was: dropping every event for those teachers). Bugfix: ActivityCreationWizard <style> inside the Vue template was silently stripped — moved the styles to an injected runtime <style> block. Bugfix: TeacherDashboard.js v-calendar was passing toISOString() strings which v-calendar's parseTimestamp rejects — switched back to Date objects.
$plugin->version   = 20260815000;         // ACADEMIC HISTORY PHASE 1: gmk_course_attempts (per-enrolment immutable attempts), gmk_academic_movements (append-only per-event grade log), gmk_movement_deletion_log (audit of annulments). New capabilities view_movement_audit + annul_movement. New classes local_grupomakro_academic_movement_manager + local_grupomakro_academic_grade_resolver. CLI cli/migrate_academic_movements.php backfills attempts and movements from gmk_course_progre + gmk_revalidations (idempotent, non-destructive). CLI cli/test_resolver_policy.php validates best-grade policy (MAX grade, effective_at DESC tie-break, annulment handling, active-attempt status). Existing UI and resolvers are untouched in this phase.
$plugin->version   = 20260816000;         // STATUS CHANGE WIZARD: wizard de aplazar/retirar/renovar en el academic panel. Nuevas columnas origin/details en gmk_student_suspension + indice (userid,timecreated). Helper progress_manager::drop_active_courses_for_user() extraido para reuso. Nuevo status_change_manager.php con la logica de negocio. 3 nuevos AJAX: get_status_change_preview, execute_status_change, get_status_change_history. Renovar se vuelve idempotente: si el estudiante esta retirado/aplazado/suspendido/desertor lo reactiva (flip a activo + drop cursos activos) y propone el ultimo periodo lectivo que inicio (o el proximo si estamos en receso); los avances normales mantienen el comportamiento previo. Inscripcion (enroll_student, manual_enroll, failed_subjects/enroll_student, enroll_module) bloquea si local_learning_users.status IN (retirado,aplazado). Nuevo componente statusChangeWizard.js con v-stepper de 5 pasos; studenttable.js reemplaza el boton Renovar por v-menu de 3 opciones; grademodal.js agrega tab de historial academico con v-timeline alimentado por gmk_student_suspension. Integracion con Odoo via Express: 3 endpoints nuevos (GET pending-invoices, POST aplazar, POST retirar) protegidos con X-Api-Key opcional. Lado Odoo: refactor de wizard_aplazar_estudiante.py para exponer do_aplazo() reusable + soporte retiro; nuevo controller aplazo_api.py.
$plugin->version   = 20260817000;         // ATTENDANCE SUPPORT UPLOAD + MARKS HISTORY TAB: when marking a session as present via absence_dashboard the operator now must upload a PDF/JPG/PNG support file (10MB cap) which is stored in the new local_grupomakro_core/attendance_support filearea keyed by attendance_log.id; the sessions modal gains a 'Historial de marcaciones' tab listing every mark made from the dashboard together with a 'Ver soporte' link that opens the file in a new tab through the extended file_proxy.php. No DB schema change (uses attendance_log.remarks + Moodle file storage).
$plugin->version   = 20260818000;         // FINANCIAL STATUS REAL-TIME: new gmk_financial_webhook_dlq table (failed Moodle financial webhook events for manual retry); new endpoint pages/financial_webhook.php that receives HMAC-signed pushes from Express /api/odoo/cache/invalidate and refreshes gmk_financial_status per partner_vat; new CLI cli/sync_financial_all.php for offline bootstraps; new lightweight WS local_grupomakro_get_financial_counts powering the 3-card indicator (total / al-dia / en-mora) on academicpanel.php with 60s polling; hook in user_login_handler.php to refresh per-student financial status on login (throttled to 6h, no-op if fresh); update_financial_status cron rescheduled to every 6h instead of daily, restricted to rows with lastupdated > 24h; new admin page pages/financial_webhook_dlq.php to inspect and retry failed webhook deliveries; new pages/financial_health.php health endpoint.
$plugin->version   = 20260819000;         // BUGFIX DATA-LOSS reprogramacion de clases VIRTUALES (type 1): la rama virtual de reschedule_class_activity asumia que $params['moduleId'] siempre era el BBB y ejecutaba course_delete_module() sobre el. Como el calendario de schedules.php envia el attendancemoduleid cuando el evento proviene de una sesion de asistencia (complete_class_event_information), reprogramar desde ese evento BORRABA la actividad Asistencia completa con todas sus sesiones, su item de calificacion y sus eventos de calendario, y creaba un BBB huerfano con relacion vacia (attendancemoduleid=0). Ahora la rama virtual resuelve explicitamente ambos modulos (attendance + BBB) desde gmk_bbb_attendance_relation, con fallback por el sessdate codificado en el nombre del BBB, y replica el flujo de la clase mixta: crea el BBB nuevo, borra el viejo, reemplaza la sesion de asistencia con replace_attendance_session() y re-vincula la relacion + gmk_class.bbbmoduleids. Nuevo guard gmk_delete_bbb_module_safely() que rechaza borrar cualquier cm que no sea bigbluebuttonbn; aplicado a las 4 rutas de borrado de BBB del reschedule (type 0/bbb, type 0/attendance, type 1, type 2).
$plugin->version   = 20260820000;         // CACHE INVALIDATION en cambios de horario: nueva gmk_invalidate_schedule_caches() llamada desde reschedule_class_activity, gmk_delete_class_activity, gmk_copy_class_activity y create_class_activities. Antes, reprogramar/eliminar/copiar una sesion dejaba el calendario de schedules.php y el panel del docente mostrando datos viejos hasta 120s (TTL de teacher_calendar_events y teacher_dashboard), porque ninguna mutacion los invalidaba: la invalidacion que existia en copy/delete borraba gmkclass_enriched y gmkbbbatrel, cachés declaradas en db/caches.php que ningun codigo lee (su unico accesor gmk_muc() no se usa). Ahora teacher_calendar_events se purga (sus claves incluyen el rango de fechas de cada visor, no enumerables) una sola vez por request, y teacher_dashboard se invalida por usuario afectado (instructor + miembros del grupo + siteadmins) para no forzar el recalculo caro a todos los docentes.
$plugin->version   = 20260821000;         // FIX excepciones de tarea (assign_overrides) ignoradas en el LXP: due_date_has_passed() leia la duedate cruda de la fila {assign} y solo sumaba assign_user_flags.extensionduedate, asi que una Excepcion de usuario/grupo no movia la fecha y el alumno veia la tarea cerrada. mod_assign solo fusiona los overrides en la instancia si se llama a update_effective_access(), cosa que ni get_instance() ni submissions_open() hacen. Nueva effective_dates() que aplica update_effective_access() + la prorroga individual; se usa en la comprobacion de cierre duro, en submit_activity y en las fechas devueltas al alumno (antes mostraba la fecha global, no la suya). Caso Aleyda Ramos, tarea 1090.
$plugin->requires = 2014051200;
$plugin->maturity = MATURITY_STABLE;
