<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Grupo Makro Core is a plugin used by the various components developed for the Grupo Makro platform.
 *
 * @package    local_grupomakro_core
 * @copyright  2022 Solutto Consulting <devs@soluttoconsulting.com>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$functions = array(
    'local_grupomakro_create_user' => array(
        'classname' => 'local_grupomakro_core\external\create_user',
        'methodname' => 'execute',
        'description' => 'Ths method creates a new user in the Moodle platform.',
        'type' => 'write',
        "ajax" => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_get_user_status' => array(
        'classname' => 'local_grupomakro_core\external\get_user_status',
        'methodname' => 'execute',
        'description' => 'Returns the status of the user in the Moodle platform.',
        'type' => 'read',
        "ajax" => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_create_class' => array(
        'classname'     => 'local_grupomakro_core\external\gmkclass\create_class',
        'methodname'    => 'execute',
        'description'   => 'Create new class',
        'type'          => 'write',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_list_classes' => array(
        'classname'     => 'local_grupomakro_core\external\gmkclass\list_classes',
        'methodname'    => 'execute',
        'description'   => 'This method list the created classes',
        'type'          => 'read',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_delete_class' => array(
        'classname'     => 'local_grupomakro_core\external\gmkclass\delete_class',
        'methodname'    => 'execute',
        'description'   => 'This method delete the class with the id provided',
        'type'          => 'write',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_update_class' => array(
        'classname'     => 'local_grupomakro_core\external\gmkclass\update_class',
        'methodname'    => 'execute',
        'description'   => 'This method update the class with the id provided',
        'type'          => 'write',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_get_potential_class_teachers' => array(
        'classname'     => 'local_grupomakro_core\external\gmkclass\get_potential_class_teachers',
        'methodname'    => 'execute',
        'description'   => 'This method get the potential class teachers',
        'type'          => 'read',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_get_teacher_available_courses' => array(
        'classname' => 'local_grupomakro_core\external\gmkclass\get_teacher_available_courses',
        'methodname' => 'execute',
        'description' => 'Get the teacher learning plan period available courses according to his/her skills',
        'type' => 'read',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_get_teacher_available_days' => array(
        'classname' => 'local_grupomakro_core\external\gmkclass\get_teacher_available_days',
        'methodname' => 'execute',
        'description' => 'Get the teacher available days for the selected class time range',
        'type' => 'read',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_calendar_get_calendar_events' => array(
        'classname' => 'local_grupomakro_core\external\event\get_calendar_events',
        'methodname' => 'execute',
        'description' => 'Get calendar events',
        'type' => 'read',
        'capabilities' => 'moodle/course:ignoreavailabilityrestrictions, moodle/calendar:manageentries, moodle/calendar:manageownentries, moodle/calendar:managegroupentries',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_send_reschedule_message' => array(
        'classname' => 'local_grupomakro_core\external\activity\send_reschedule_message',
        'methodname' => 'execute',
        'description' => '',
        'type' => 'read',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_get_teachers_disponibility' => array(
        'classname' => 'local_grupomakro_core\external\disponibility\get_teachers_disponibility',
        'methodname' => 'execute',
        'description' => 'Get the teachers disponibility',
        'type' => 'read',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_add_teacher_disponibility' => array(
        'classname' => 'local_grupomakro_core\external\disponibility\add_teacher_disponibility',
        'methodname' => 'execute',
        'description' => 'Add teacher disponibility record',
        'type' => 'write',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_update_teacher_disponibility' => array(
        'classname' => 'local_grupomakro_core\external\disponibility\update_teacher_disponibility',
        'methodname' => 'execute',
        'description' => 'Update teacher disponibility record',
        'type' => 'write',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_delete_teacher_disponibility' => array(
        'classname' => 'local_grupomakro_core\external\disponibility\delete_teacher_disponibility',
        'methodname' => 'execute',
        'description' => 'Delete a teacher disponibility record',
        'type' => 'write',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_get_teachers_disponibility_calendar' => array(
        'classname' => 'local_grupomakro_core\external\disponibility\get_teachers_disponibility_calendar',
        'methodname' => 'execute',
        'description' => 'Get the theachers disponibility for the disponibility calendar',
        'type' => 'read',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_check_reschedule_conflicts' => array(
        'classname' => 'local_grupomakro_core\external\activity\check_reschedule_conflicts',
        'methodname' => 'execute',
        'description' => 'Check if the new date and time for the activity is in conflict with another class for the users in the update activity',
        'type' => 'read',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_reschedule_activity' => array(
        'classname' => 'local_grupomakro_core\external\activity\reschedule_activity',
        'methodname' => 'execute',
        'description' => 'Reschedule an activity to another date and time',
        'type' => 'write',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_create_institution' => array(
        'classname' => 'local_grupomakro_core\external\institution\create_institution',
        'methodname' => 'execute',
        'description' => 'Create a new institution',
        'type' => 'write',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_update_institution' => array(
        'classname' => 'local_grupomakro_core\external\institution\update_institution',
        'methodname' => 'execute',
        'description' => 'Update an institution',
        'type' => 'write',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_list_institutions' => array(
        'classname' => 'local_grupomakro_core\external\institution\list_institutions',
        'methodname' => 'execute',
        'description' => 'Update an institution',
        'type' => 'read',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_delete_institution' => array(
        'classname' => 'local_grupomakro_core\external\institution\delete_institution',
        'methodname' => 'execute',
        'description' => 'Update an institution',
        'type' => 'write',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_create_institution_contract' => array(
        'classname' => 'local_grupomakro_core\external\institutionContract\create_institution_contract',
        'methodname' => 'execute',
        'description' => 'Update an institution',
        'type' => 'write',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_update_institution_contract' => array(
        'classname' => 'local_grupomakro_core\external\institutionContract\update_institution_contract',
        'methodname' => 'execute',
        'description' => 'Update an institution',
        'type' => 'write',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_delete_institution_contract' => array(
        'classname' => 'local_grupomakro_core\external\institutionContract\delete_institution_contract',
        'methodname' => 'execute',
        'description' => 'Update an institution',
        'type' => 'write',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_list_institution_contracts' => array(
        'classname' => 'local_grupomakro_core\external\institutionContract\list_institution_contracts',
        'methodname' => 'execute',
        'description' => 'Update an institution',
        'type' => 'read',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_create_contract_user' => array(
        'classname' => 'local_grupomakro_core\external\contractUser\create_contract_user',
        'methodname' => 'execute',
        'description' => 'Update an institution',
        'type' => 'write',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_update_contract_user' => array(
        'classname' => 'local_grupomakro_core\external\contractUser\update_contract_user',
        'methodname' => 'execute',
        'description' => 'Update an institution',
        'type' => 'write',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_delete_contract_user' => array(
        'classname' => 'local_grupomakro_core\external\contractUser\delete_contract_user',
        'methodname' => 'execute',
        'description' => 'Delete a contract user record',
        'type' => 'write',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_list_contract_users' => array(
        'classname' => 'local_grupomakro_core\external\contractUser\list_contract_users',
        'methodname' => 'execute',
        'description' => 'Update an institution',
        'type' => 'read',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_generate_contract_enrol_link' => array(
        'classname' => 'local_grupomakro_core\external\contractUser\generate_contract_enrol_link',
        'methodname' => 'execute',
        'description' => 'generate a link for the users to enrol in a course related to a contract',
        'type' => 'write',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_create_student_user' => array(
        'classname' => 'local_grupomakro_core\external\contractUser\create_student_user',
        'methodname' => 'execute',
        'description' => 'Create a user and enrol in a course contract',
        'type' => 'write',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_bulk_create_contract_user' => array(
        'classname' => 'local_grupomakro_core\external\contractUser\bulk_create_contract_user',
        'methodname' => 'execute',
        'description' => 'Create a user and enrol in a course contract',
        'type' => 'write',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_get_student_active_classes' => array(
        'classname' => 'local_grupomakro_core\external\student\get_student_active_classes',
        'methodname' => 'execute',
        'description' => 'Get the student active classes',
        'type' => 'read',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_student_class_enrol' => array(
        'classname' => 'local_grupomakro_core\external\student\student_class_enrol',
        'methodname' => 'execute',
        'description' => 'Enrol a student in a class group',
        'type' => 'write',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_get_student_learning_plans_overview' => array(
        'classname' => 'local_grupomakro_core\external\student\get_student_learning_plans_overview',
        'methodname' => 'execute',
        'description' => 'Gets the student learning plans overview',
        'type' => 'read',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_get_student_learning_plan_pensum' => array(
        'classname' => 'local_grupomakro_core\external\student\get_student_learning_plan_pensum',
        'methodname' => 'execute',
        'description' => 'Gets the student learning plans pensum',
        'type' => 'read',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_get_student_course_pensum_activities' => array(
        'classname' => 'local_grupomakro_core\external\student\get_student_course_pensum_activities',
        'methodname' => 'execute',
        'description' => 'Gets the student course pensum activities',
        'type' => 'read',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    
    'local_grupomakro_approve_course_class_schedules' => array(
        'classname' => 'local_grupomakro_core\external\schedule\approve_course_class_schedules',
        'methodname' => 'execute',
        'description' => 'Approve a class schedule and enrol all the students in pre-registry and queue tables in its group',
        'type' => 'write',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_change_students_schedules' => array(
        'classname' => 'local_grupomakro_core\external\schedule\change_students_schedules',
        'methodname' => 'execute',
        'description' => 'Change the student(s) schedules from one class to another, either but puting them in the class pre-registry table or if full in the class queue table',
        'type' => 'write',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_delete_course_class_schedule' => array(
        'classname' => 'local_grupomakro_core\external\schedule\delete_course_class_schedule',
        'methodname' => 'execute',
        'description' => 'Delete a class and all the linked records from pre-registry and queue tables, save a message with the reason',
        'type' => 'write',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_delete_student_from_class_schedule' => array(
        'classname' => 'local_grupomakro_core\external\schedule\delete_student_from_class_schedule',
        'methodname' => 'execute',
        'description' => 'Delete a student from class pre-registry table or queue table otherwise',
        'type' => 'write',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_get_class_schedules_queues' => array(
        'classname' => 'local_grupomakro_core\external\schedule\get_class_schedules_queues',
        'methodname' => 'execute',
        'description' => 'Get the students info from que course classes schedule queue',
        'type' => 'read',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_get_course_class_schedules' => array(
        'classname' => 'local_grupomakro_core\external\schedule\get_course_class_schedules',
        'methodname' => 'execute',
        'description' => 'Get the course class schedules for an specific course and period',
        'type' => 'read',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_get_course_class_schedules_overview' => array(
        'classname' => 'local_grupomakro_core\external\schedule\get_course_class_schedules_overview',
        'methodname' => 'execute',
        'description' => 'Get the course class schedules for the created courses and periods',
        'type' => 'read',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_get_course_students_by_class_schedule' => array(
        'classname' => 'local_grupomakro_core\external\schedule\get_course_students_by_class_schedule',
        'methodname' => 'execute',
        'description' => 'Get the students from both pre-registry table and queue table for an specific class',
        'type' => 'read',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_get_scheduleless_students' => array(
        'classname' => 'local_grupomakro_core\external\schedule\get_scheduleless_students',
        'methodname' => 'execute',
        'description' => 'Get the students without schedule for an specific course',
        'type' => 'write',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_bulk_update_teachers_disponibility' => array(
        'classname' => 'local_grupomakro_core\external\disponibility\bulk_update_teachers_disponibility',
        'methodname' => 'execute',
        'description' => 'Bulk update teacher disponibilities',
        'type' => 'write',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_close_current_period' => array(
        'classname' => 'local_grupomakro_core\external\period\close_current_period',
        'methodname' => 'execute',
        'description' => 'Close current period and update the learning plan users periods and courses',
        'type' => 'write',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_get_learning_plan_list' => array(
        'classname' => 'local_grupomakro_core\external\learningPlan\get_learning_plan_list',
        'methodname' => 'execute',
        'description' => 'Get the learning plans list for the moodle administrative panel',
        'type' => 'read',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_get_learning_plan_pensum' => array(
        'classname' => 'local_grupomakro_core\external\learningPlan\get_learning_plan_pensum',
        'methodname' => 'execute',
        'description' => 'Get the learning plan pensum',
        'type' => 'read',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
       'local_grupomakro_get_student_info' => array(
        'classname' => 'local_grupomakro_core\external\student\get_student_info',
        'methodname' => 'execute',
        'description' => 'Get information about all students',
        'type' => 'read',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
   'local_grupomakro_student_class_revalid_enrol' => array(
        'classname' => 'local_grupomakro_core\external\student\student_class_revalid_enrol',
        'methodname' => 'execute',
        'description' => 'Enrol a student in the corresponding revalid group',
        'type' => 'write',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
   'local_grupomakro_student_get_revalids' => array(
        'classname' => 'local_grupomakro_core\external\student\student_get_revalids',
        'methodname' => 'execute',
        'description' => 'Get the active revalids activities for an user',
        'type' => 'read',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_upload_academic_calendar_period' => array(
        'classname' => 'local_grupomakro_core\external\period\upload_academic_calendar_period',
        'methodname' => 'execute',
        'description' => 'Upload an academic calendar period',
        'type' => 'write',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_get_academic_calendar_period' => array(
        'classname' => 'local_grupomakro_core\external\period\get_academic_calendar_period',
        'methodname' => 'execute',
        'description' => 'Get an academic calendar period',
        'type' => 'read',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_get_bbb_module_url' => array(
        'classname' => 'local_grupomakro_core\external\activity\get_bbb_module_url',
        'methodname' => 'execute',
        'description' => 'Get the URL of the BBB session or recording',
        'type' => 'read',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'local_grupomakro_mark_bbb_attendance_by_playback' => array(
        'classname' => 'local_grupomakro_core\external\activity\mark_bbb_attendance_by_playback',
        'methodname' => 'execute',
        'description' => 'Get the URL of the BBB session or recording',
        'type' => 'write',
        'capabilities' => '',
        'ajax'          => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
);